// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.Data.DatabaseAccess;

namespace VMS.Data.Migrations
{
    [DbContext(typeof(VMSContext))]
    partial class VMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157");

            modelBuilder.Entity("VMS.Data.Models.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("UiName");

                    b.Property<int>("VehicleTypeId");

                    b.HasKey("Id");

                    b.ToTable("Attribute");

                    b.HasData(
                        new { Id = 1, Name = "Doors", UiName = "Doors", VehicleTypeId = 1 },
                        new { Id = 2, Name = "Engine", UiName = "Engine", VehicleTypeId = 1 },
                        new { Id = 3, Name = "BodyType", UiName = "Body Type", VehicleTypeId = 1 },
                        new { Id = 4, Name = "Wheel", UiName = "Wheels", VehicleTypeId = 1 }
                    );
                });

            modelBuilder.Entity("VMS.Data.Models.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttributeId");

                    b.Property<string>("Value");

                    b.Property<int>("VehicleId");

                    b.HasKey("Id");

                    b.ToTable("AttributeValue");
                });

            modelBuilder.Entity("VMS.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<int>("VehicleTypeId");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("VMS.Data.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleType");

                    b.HasData(
                        new { Id = 1, Name = "Car" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
